# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RiskGuard
                                 A QGIS plugin
 test
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-07
        copyright            : (C) 2024 by Alessio Corsini
        email                : alessio.corsini@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RiskGuard class from file RiskGuard.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .riskGuard import RiskGuard
    return RiskGuard(iface)
